version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    CLUSTER_NAME: prod-eks-cluster

phases:
  pre_build:
    commands:
      - echo Updating kubeconfig
      - aws eks update-kubeconfig --region us-east-1 --name prod-eks-cluster --role-arn arn:aws:iam::772693223288:role/service-role/codebuild-eks-deploy-service-role-2

  build:
    commands:
      - echo Deploying to EKS
      - kubectl apply -f k8s/

  post_build:
    commands:
      - echo "Deployment completed successfully"
