version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    CLUSTER_NAME: prod-eks-cluster

phases:
  pre_build:
    commands:
      - echo "Caller identity:"
      - aws sts get-caller-identity
      - echo Updating kubeconfig
      - aws eks update-kubeconfig --region us-east-1 --name prod-eks-cluster 
      - export AWS_EKS_TOKEN=true
      - IMAGE_TAG=$(cat imageTag.txt)

  build:
    commands:
      - echo Deploying to EKS
      - kubectl get ns
      - sed -i "s|PLACEHOLDER|$IMAGE_TAG|g" k8s/deployment.yaml
      - kubectl apply -f k8s/ --validate=false

  post_build:
    commands:
      - echo "Deployment completed successfully"
